# Generated by Django 3.0.5 on 2020-04-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='#', max_length=300)),
                ('short_txt', models.TextField()),
                ('body_txt', models.TextField()),
                ('pic', models.TextField()),
                ('date', models.CharField(default='#', max_length=10)),
                ('writer', models.CharField(default='#', max_length=50)),
            ],
        ),
    ]
