# Generated by Django 3.0.5 on 2020-04-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='body_txt',
            new_name='newsContent',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='pic',
            new_name='newsImage',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='short_txt',
            new_name='newsSummary',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='publishDate',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='writer',
            new_name='writerName',
        ),
        migrations.RemoveField(
            model_name='news',
            name='name',
        ),
        migrations.AddField(
            model_name='news',
            name='catId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='catName',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
