# Generated by Django 3.0.5 on 2020-04-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200422_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
