# Generated by Django 3.0.5 on 2020-04-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_newsname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='newsName',
            new_name='newsImageName',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='newsImage',
            new_name='newsImageUrl',
        ),
    ]
