# Generated by Django 3.0.5 on 2020-04-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200422_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsImageUrl',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='publishDate',
            field=models.CharField(default='#', max_length=20),
        ),
    ]
