# Generated by Django 3.0.5 on 2020-04-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200422_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsImageUrl',
            field=models.ImageField(upload_to=''),
        ),
    ]
