# Generated by Django 3.0.5 on 2020-04-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200422_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ocatId',
            field=models.IntegerField(default=0),
        ),
    ]
