# Generated by Django 3.0.5 on 2020-04-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_news_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='PublisherName',
            field=models.CharField(default='#', max_length=300),
        ),
    ]
