# Generated by Django 3.0.5 on 2020-04-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20200501_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsImageUrl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
