# Generated by Django 3.0.5 on 2020-05-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_news_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('newsSummary', models.TextField(blank=True, null=True)),
                ('newsImageUrl', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('newsImageName', models.CharField(blank=True, max_length=300, null=True)),
                ('publishDate', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('writerName', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('catName', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('catId', models.IntegerField(blank=True, default=0, null=True)),
                ('ocatId', models.IntegerField(blank=True, default=0, null=True)),
                ('tag', models.TextField(blank=True, default=None, max_length=300, null=True)),
                ('act', models.IntegerField(blank=True, default=0, null=True)),
                ('publisherName', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
        ),
    ]
