# Generated by Django 3.0.5 on 2020-05-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='catId',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='catName',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='newsSummary',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='tag',
        ),
        migrations.AddField(
            model_name='headline',
            name='newsUrl',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='newUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
