# Generated by Django 3.0.5 on 2020-05-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20200501_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='newUrl',
            new_name='newsUrl',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='newsImageName',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='newsImageUrl',
        ),
        migrations.AddField(
            model_name='news',
            name='source_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
