# Generated by Django 3.0.5 on 2020-05-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20200501_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='time',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
