# Generated by Django 3.0.5 on 2020-04-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactUserTxt', models.CharField(default=' ', max_length=50)),
                ('isPhoneNo', models.IntegerField(default=0)),
            ],
        ),
    ]
