# Generated by Django 3.0.5 on 2020-04-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='#', max_length=300)),
                ('email', models.CharField(default='#', max_length=300)),
                ('message', models.TextField(default=' ')),
            ],
        ),
    ]
