# Generated by Django 3.0.5 on 2020-04-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AddField(
            model_name='contactform',
            name='time',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
