# Generated by Django 3.0.5 on 2020-04-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='countNews',
            field=models.IntegerField(default=0),
        ),
    ]
