# Generated by Django 3.0.5 on 2020-04-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_cat_countnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='countNews',
            new_name='newsCount',
        ),
    ]
