# Generated by Django 3.0.5 on 2020-05-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_auto_20200423_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='headlineCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cat',
            name='catName',
            field=models.CharField(default='', max_length=300),
        ),
    ]
