# Generated by Django 3.0.5 on 2020-04-21 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='about',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
