# Generated by Django 3.0.5 on 2020-04-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200424_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='aboutText',
            field=models.TextField(default=' '),
        ),
    ]
