# Generated by Django 3.0.5 on 2020-04-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('cm', models.TextField()),
                ('newsId', models.IntegerField(default=0)),
                ('date', models.CharField(default='', max_length=12)),
                ('time', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
