# Generated by Django 3.0.5 on 2020-04-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='manager',
            name='u_name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
