# Generated by Django 3.0.5 on 2020-04-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_manager_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='manager',
            name='u_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user_ip',
            field=models.TextField(default=''),
        ),
    ]
