# Generated by Django 3.0.5 on 2020-05-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200427_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
